version: '3.6'
services:
  mysql-master:
    image: 'mysql:5.7.31'
    container_name: mysql-master
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ../data:/var/lib/mysql
      - ../conf/my.cnf:/etc/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample
      MYSQL_USER: rn
      MYSQL_PASSWORD: rn1234