version: '3.6'
services:
 redis:
  image: redis:5.0.9
  container_name: redis-6382
  restart: always
  ports:
    - 6382:6382   # redis的服务端口
    - 16382:16382 # redis集群监控端口
  volumes:
    - ../data:/data
    - ../conf/redis.conf:/usr/local/etc/redis/redis.conf
    - /etc/localtime:/etc/localtime:ro
  command: redis-server /usr/local/etc/redis/redis.conf

