version: '3.6'

services:
  zk1:
    image: zookeeper:3.6.2
    restart: always
    container_name: zk1
    ports:
      - "2181:2181"
    volumes:
      - "../data/zk1/data:/data"
      - "../data/zk1/datalog:/datalog"
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181

  zk2:
    image: zookeeper:3.6.2
    restart: always
    container_name: zk2
    ports:
      - "2182:2181"
    volumes:
      - "../data/zk2/data:/data"
      - "../data/zk2/datalog:/datalog"
    environment:
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181

  zk3:
    image: zookeeper:3.6.2
    restart: always
    container_name: zk3
    ports:
      - "2183:2181"
    volumes:
      - "../data/zk3/data:/data"
      - "../data/zk3/datalog:/datalog"
    environment:
      - ZOO_MY_ID=3
      - ZOO_SERVERS=server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181
