filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false
filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/logs/*.log

setup.template.setting:
  index.number_of_shards: 1
  number_of_replicas: 0

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: elastic
  password: elastic
