groups:
  - name: example   #报警规则的名字
    rules:
      # Alert for any instance that is unreachable for >5 minutes.
      - alert: InstanceDown     #检测job的状态，持续1分钟metrices不能访问会发给altermanager进行报警
        expr: up == 0
        for: 1m    #持续时间
        labels:
          serverity: page
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."