version: '3.6'

services:
  elasticsearch:
    image: elasticsearch:7.10.1
    container_name: elasticsearch
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
#      - ../elasticsearch/data:/usr/share/elasticsearch/data
      - ../elasticsearch/logs/:/usr/share/logs/
      - ../elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    environment:
      discovery.type: single-node
      ELASTIC_PASSWORD: elastic
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"

  logstash:
    image: logstash:7.10.1
    container_name: logstash
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    volumes:
      - ../logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ../logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:7.10.1
    container_name: kibana
    ports:
      - "5601:5601"
    volumes:
      - ../kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    depends_on:
      - elasticsearch

networks:
  default:
    external:
      name: elk_net
