version: '3.6'

services:
  elasticsearch:
    image: elasticsearch:7.10.1
    container_name: elasticsearch
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
#      - ../elasticsearch/data:/usr/share/elasticsearch/data
      - ../elasticsearch/logs/:/usr/share/logs/
      - ../elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    environment:
      discovery.type: single-node
      ELASTIC_PASSWORD: elastic
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"

  kibana:
    image: kibana:7.10.1
    container_name: kibana
    restart: always
    ports:
      - "5601:5601"
    volumes:
      - ../kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    depends_on:
      - elasticsearch

  logstash:
    image: logstash:7.10.1
    container_name: logstash
    restart: always
    ports:
      - "5044:5044"
      - "5045:5045"
    volumes:
      - ../logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ../logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    depends_on:
      - elasticsearch

  filebeat:
    image: elastic/filebeat:7.10.1
    container_name: filebeat
    restart: always
    volumes:
      - ../filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ../filebeat/data/logs/:/data/logs/
    user: root
    depends_on:
      - logstash

networks:
  default:
    external:
      name: elk_net
