version: '3.6'

services:
  nginx:
    image: nginx:1.17.5
    container_name: nginx
    restart: always
    network_mode: bridge
    ports:
      - "80:80" #HTTP_PORT
      - "443:443"
    volumes:
      - ./data/static:/usr/share/nginx/static
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/conf.d:/etc/nginx/conf.d:ro
      - ./conf/cert:/etc/nginx/cert:ro
      - ./logs:/var/log/nginx
