version: '3.6'

services:
  kafka1:
    image: wurstmeister/kafka:2.13-2.7.0
    restart: always
    container_name: kafka1
    ports:
      - "9091:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.125.131:9091
      - KAFKA_ADVERTISED_HOST_NAME=192.168.125.131
      - KAFKA_ADVERTISED_PORT=9091
      - KAFKA_ZOOKEEPER_CONNECT=192.168.125.131:2181,192.168.125.131:2182,192.168.125.131:2183
      - JMX_PORT=9991
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "../data/kafka1/:/kafka"

  kafka2:
    image: wurstmeister/kafka:2.13-2.7.0
    restart: always
    container_name: kafka2
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.125.131:9092
      - KAFKA_ADVERTISED_HOST_NAME=192.168.125.131
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=192.168.125.131:2181,192.168.125.131:2182,192.168.125.131:2183
      - JMX_PORT=9992
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "../data/kafka2/:/kafka"

  kafka3:
    image: wurstmeister/kafka:2.13-2.7.0
    restart: always
    container_name: kafka3
    ports:
      - "9093:9092"
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.125.131:9093
      - KAFKA_ADVERTISED_HOST_NAME=192.168.125.131
      - KAFKA_ADVERTISED_PORT=9093
      - KAFKA_ZOOKEEPER_CONNECT=192.168.125.131:2181,192.168.125.131:2182,192.168.125.131:2183
      - JMX_PORT=9993
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "../data/kafka3/:/kafka"

  kafka-manager:
    image: sheepkiller/kafka-manager:1.3.1.6
    restart: always
    container_name: kafa-manager
    ports:
      - "9002:9000"
    environment:
      - ZK_HOSTS=192.168.125.131:2181,192.168.125.131:2182,192.168.125.131:2183
      - KAFKA_BROKERS=192.168.125.131:9091,192.168.125.131:9092,192.168.125.131:9093
      - APPLICATION_SECRET=letmein
      - KM_ARGS=-Djava.net.preferIPv4Stack=true
