version: '3.6'
services:
  sonarqube:
    image: sonarqube:7.9-community
    container_name: sonarqube
    restart: always
    environment:
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    volumes:
      - /etc/localtime:/etc/localtime:ro

  db:
    image: postgres:12.1
    container_name: postgres
    restart: always
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - ../data/postgresql:/var/lib/postgresql
      - ../data/postgresql/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro

networks:
  sonarnet:
    driver: bridge
