version: '3.6'

services:
  zk:
    image: zookeeper:3.6.2
    restart: always
    container_name: zk
    ports:
      - "2181:2181"
    volumes:
      - "../data/zk/data:/data"
      - "../data/zk/datalog:/datalog"
  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    restart: always
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.125.102:9092
      - KAFKA_ADVERTISED_HOST_NAME=192.168.125.102
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=192.168.125.102:2181
      - JMX_PORT=9999
    volumes:
      - "../data/kafka1/:/kafka"
      - "/var/run/docker.sock:/var/run/docker.sock"
