version: '3.6'

services:
  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    restart: always
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.125.131:9092
      - KAFKA_ADVERTISED_HOST_NAME=192.168.125.131
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=192.168.125.131:2181
      - JMX_PORT=9999
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "../data/kafka1/:/kafka"
