version: '3.6'
services:
  mysql:
    image: 'mysql:8.0.22'
    container_name: mysql
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ../data/mysql:/var/lib/mysql
      - ../conf/my.cnf:/etc/my.cnf
      - ../init:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default_db
      TZ: Asia/Shanghai