version: '3.6'
services:
  mysql:
    image: 'mysql:5.7.30'
    container_name: mysql
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ../data/mysql:/var/lib/mysql
      - ../conf/my.cnf:/etc/my.cnf
      - ../init:/docker-entrypoint-initdb.d/

