version: "3.6"
services:
  dns:
    image: sameersbn/bind:9.16.1-20200524
    container_name: dns
    restart: always
    ports:
      - '10000:10000'
      - '53:53'
      - '53:53/udp'
    volumes:
      - ../data:/data
    environment:
      - ROOT_PASSWORD=root
